### ISSUE TITLE
Re-write the Ansible scripts to install Config Sync via the gcloud method

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/point-of-sale#13]
### What?
- The current scripts in the repository uses the [manual installation method](https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl) for Config Sync using **kubectl** which is unsupported
- As a result this can lead to bugs that can be hard to track: [b/200555955](http://b/200555955) ***(internal link)***
- Thus, we would to re-write the ACM installation in the Ansible scripts to use the [`gcloud` based method](https://cloud.google.com/anthos-config-management/docs/how-to/installing)

**Comment by bourgeoisor** [comment]
@Shabirmean is this issue still active?

**Comment by Shabirmean** [comment]
Closing this issue in favor of https://github.com/GoogleCloudPlatform/anthos-samples/issues/311 since the related sample has been moved to the anthos-samples repo
