### ISSUE TITLE
Reduce Ansible installation time by bundling static steps into the VM image

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/point-of-sale#15]
### What? 

As per the current state of the Ansible installation scripts the process takes ***~35 minutes*** to complete. We can reduce this time by bundling some of the static steps in the Ansible scripts **(that does not change with the _host_vars_)** into a VM image.

This can make the quick start experience much better by reducing the time it takes to reach completion.

#### Notes:
- Everything up to `abm-install` can be packaged into an image
- The image needs to be available to both **GCE** and **physical machines**
- Explore using [Packer Qemu builder](https://www.packer.io/docs/builders/qemu) to create the images
- We can try building the image for QEMU in GCP and converting it

**Comment by Shabirmean** [comment]
@mike-ensor - tagging you for visibility of this suggestion

**Comment by bourgeoisor** [comment]
@Shabirmean is this issue still active?

**Comment by Shabirmean** [comment]
The improvement is still relavant but the sample has been moved to the anthos-samples repo. SO closing this in favor of https://github.com/GoogleCloudPlatform/anthos-samples/issues/310

**Comment by mike-ensor** [comment]
@bourgeoisor yes, we've started down a path to create a Packer version of most of the ABM Install (everything up to `bmctl create`) ...just going a bit slow due to low human resources
