### ISSUE TITLE
Upgrade from Java 11?

### ISSUE THREAD

**Issue by mathieu-benoit** [GoogleCloudPlatform/point-of-sale#180]
Any particular reason why PoS apps are with Java 11? Any plan to move them to 17 (LTS) or 18 or even 19?

FYI:
- Online Boutique is now in [18](https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/adservice), soon in [19](https://github.com/GoogleCloudPlatform/microservices-demo/pull/1132)
- BoA is now in [17](https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/src/balancereader/pom.xml#L35):

**Comment by bourgeoisor** [comment]
18 is [not supported](https://en.wikipedia.org/wiki/Java_version_history#Release_table) anymore, so ideally either 17 (LTS) or 19 (latest).

**Comment by bourgeoisor** [comment]
@Shabirmean any technical reason for Java 11, or can those be bumped up to currently supported versions?

**Comment by NimJay** [comment]
**Updating to cool down out-of-SLO list:**
It looks like Olivier is working on upgrading to Java 17 in https://github.com/GoogleCloudPlatform/point-of-sale/pull/188.

**Comment by bourgeoisor** [comment]
Still WIP, small issue which should be taken care of when https://github.com/GoogleContainerTools/skaffold/issues/7076 gets fixed in the next release of Skaffold.
