### ISSUE TITLE
Add unit tests for the payments service

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/point-of-sale#92]
### Description
- Payments service requires unit tests
   - Controller class
   - Connector for Database
   - Connector for InMemory

**Comment by bourgeoisor** [comment]
I think we should still do this -- reseting SLO.

**Comment by NimJay** [comment]
* Unit testing each class would be ideal.
* But it's not a priority. (I don't think our team can afford granular unit tests.)
* As long as we have high-level (integration) tests in place that test deployments of Point of Sale (using both the in-memory database and MySQL), we can be confident that the Payments Service. @Shabirmean has done a stellar job of setting up these integration tests. Example [comment here](https://github.com/GoogleCloudPlatform/point-of-sale/pull/261#issuecomment-1767243431).
* I'm closing this.

**Comment by NimJay** [comment]
I realize we don't actually have end-to-end testing of our CI/CD/automated deployments in place. We'll track the end-to-end testing work in https://github.com/GoogleCloudPlatform/point-of-sale/issues/94.
