### ISSUE TITLE
Add unit tests for the apiserver service 

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/point-of-sale#93]
### Description
- ApiServer service requires unit tests
   - Controller class

**Comment by bourgeoisor** [comment]
We should still do this. Commenting to reset SLO.

**Comment by NimJay** [comment]
I'm closing this for the same reason as the closure of https://github.com/GoogleCloudPlatform/point-of-sale/issues/92#issuecomment-1777180855.
